name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build binary
        run: cargo build --release

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/tiddy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

